import Head from 'next/head'    
import PageMain from '@templates/pageMain'
 

export default function Home() {  
  return (
    <>
      <Head>
        <title>Nathaniel Morales | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoicon.ico" />
      </Head> 
      < PageMain />
    </>
  )
}
