import Head from 'next/head' 
import { Noto_Serif_Hebrew } from 'next/font/google'
import style from '@stylepath/Home.module.scss'
import Image from 'next/image' 
import Logo from '@publicpath/nathlogo.png' 
const font = Noto_Serif_Hebrew({ subsets: ['hebrew'], weight:"400" })
const {className: noto, style: notostyle} = font
const { main } = style

export default function Home() {
  return (
    <>
      <Head>
        <title>Nathaniel Morales | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoicon.png" />
      </Head>
      <main className={main}> 
      <h1 style={notostyle}>Hi, I'am Nathaniel</h1>
      <Image src={Logo} alt="nath logo" />
      </main>
    </>
  )
}
